name: CI

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy Surge
      uses: yg/deploy-surge@master
      with:
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
        BUILD_DIRECTORY: ${{ secrets.BUILD_DIRECTORY }}
